# see https://s.apache.org/asfyaml
github:
  description: "Apache Maven core"
  homepage: https://maven.apache.org/ref/current
  labels:
    - java
    - build-management
    - apache-maven
    - maven
    - hacktoberfest
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true
  autolink_jira: null  # Disable JIRA autolinking
  notifications:
    commits: commits@maven.apache.org
    issues: issues@maven.apache.org
    pullrequests: issues@maven.apache.org
    jira_options:  # Remove or comment out the JIRA options if no longer needed
